# permissions for end users to view vectorsidecars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vectorsidecar-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: 696f7dc043f2c91178ad7d83
    app.kubernetes.io/part-of: 696f7dc043f2c91178ad7d83
    app.kubernetes.io/managed-by: kustomize
  name: vectorsidecar-viewer-role
rules:
- apiGroups:
  - observability.kontroloop.ai
  resources:
  - vectorsidecars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.kontroloop.ai
  resources:
  - vectorsidecars/status
  verbs:
  - get
