---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-image-pull-secret
  namespace: 696f7dc043f2c91178ad7d83-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsiYXV0aCI6ICJZVzFwZEdSbE56ZzVOamsyT21kb2IxOU5ObFF5U2tsMWFVNDJhblowZVZKbGVuVm1URVJsYUVwM2VsZFNkWG96Y1VwcmNtdz0ifX19
